# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='A/C Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='credit',
            field=models.FloatField(verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='debit',
            field=models.FloatField(verbose_name='Debit Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.CharField(max_length=200, verbose_name='Notes'),
        ),
    ]
